/*
 * This source file was generated by the Gradle 'init' task
 */
package proj.rpg.java;

/**
 * エントリポイント。
 * LWJGLでウィンドウを開き、擬似3Dダンジョンの最小レンダリングを行う。
 */
public class App {
    public static void main(String[] args) {
        new Game().run();
    }
}
