/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Javaアプリケーション
    application
}

repositories {
    // 依存解決
    mavenCentral()
}

dependencies {
    // テスト
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // LWJGL + GLFW + OpenGL + STB + JOML
    val lwjglVersion = "3.3.3"
    val lwjglNatives = "natives-windows"

    implementation(platform("org.lwjgl:lwjgl-bom:$lwjglVersion"))
    implementation("org.lwjgl:lwjgl")
    implementation("org.lwjgl:lwjgl-glfw")
    implementation("org.lwjgl:lwjgl-opengl")
    implementation("org.lwjgl:lwjgl-stb")
    implementation("org.joml:joml:1.10.5")

    runtimeOnly("org.lwjgl:lwjgl::$lwjglNatives")
    runtimeOnly("org.lwjgl:lwjgl-glfw::$lwjglNatives")
    runtimeOnly("org.lwjgl:lwjgl-opengl::$lwjglNatives")
    runtimeOnly("org.lwjgl:lwjgl-stb::$lwjglNatives")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        // Java 17+ 推奨（ローカルに21があればそのまま利用されます）
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // エントリポイント
    mainClass = "proj.rpg.java.App"
}

tasks.named<Test>("test") {
    // JUnit Platform
    useJUnitPlatform()
}
